### ISSUE TITLE
Fail to get course

### ISSUE THREAD

**Issue by rinodung** [nishad/udemy-dl-windows#1]
I tried to get a premium course: https://www.udemy.com/build-an-instant-update-database-interface-with-jquery-ajax/

But I get this error, Can you show me how to fix it?

![fail to get course id](https://cloud.githubusercontent.com/assets/7805715/9299594/be2daee8-44e7-11e5-959c-052426817aea.png)

**Comment by nishad** [comment]
You have to remove the trailing / from the course url and that'll fix the issue. Please update me the result.

**Comment by nishad** [comment]
This seems like a specific course related issue, There's something wrong with the course in udemy as I could see the URL slug and the title of the course doesn't match. So it is not a general issue.

**Comment by nishad** [comment]
Try with the latest version available here
https://github.com/nishad/udemy-dl-windows/releases/download/v1.8.0/udemy-dl-win-1.8.0.zip
