### ISSUE TITLE
pdf/text files

### ISSUE THREAD

**Issue by huiskesmartijn** [nishad/udemy-dl-windows#10]
Hey there,

Are you planning to implement support for download course files? (like PDF's and text files)

Would be a really nice feature to add. Also thanks a bunch for keeping this updated!

**Comment by nishad** [comment]
Please refer these comments 
https://github.com/nishad/udemy-dl-windows/issues/8#issuecomment-141507747
https://github.com/nishad/udemy-dl-windows/issues/4#issuecomment-137649985
