### ISSUE TITLE
[BUG] 'nonetype' object have no attribute 'group'

### ISSUE THREAD

**Issue by theglowingnation** [nishad/udemy-dl-windows#102]
Version : **2.1.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [X] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

2.1.1 "'nonetype' object have no attribute 'group' " .This was working fine till yesterday but today again this bug have appeared .

**Comment by davidyapdy** [comment]
Me too. No idea what's happening.

**Comment by nishad** [comment]
Fixed with https://github.com/nishad/udemy-dl-windows/releases/tag/v2.1.2
