### ISSUE TITLE
[BUG] Cannot download in Windows PC

### ISSUE THREAD

**Issue by anupammajhi** [nishad/udemy-dl-windows#107]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION]..

Replace everything between stars with current version of your udemy-dl.exe (output of udemy-dl.exe -v):  
Version : **2.1.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [X] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---
CLI : DOS / Powershell
OS : Windows
Course Enrolled : YES
Username & Password Checked : YES

While trying to download as per instruction, I get this error:

```
c:\Users\a055515\Desktop\udemy-dl-win-2.1.1\udemy-dl-win>udemy-dl.exe -o c:\user
s\a055515\desktop https://www.udemy.com/photography-masterclass-your-complete-gu
ide-to-photography
Username / Email : majhi.anupam@gmail.com
Password :
[INFO-881] Downloading to: c:\users\a055515\desktop

[INFO-127] Trying to log in ...
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 886, in <module>
  File "<string>", line 883, in main
  File "<string>", line 694, in udemy_dl
  File "<string>", line 129, in login
  File "<string>", line 115, in get_csrf_token
  File "<string>", line 85, in get
  File "site-packages\requests\sessions.py", line 480, in get
  File "site-packages\requests\sessions.py", line 468, in request
  File "site-packages\requests\sessions.py", line 576, in send
  File "site-packages\requests\adapters.py", line 437, in send
ConnectionError: HTTPSConnectionPool(host='www.udemy.com', port=443): Max retrie
s exceeded with url: /join/login-popup (Caused by NewConnectionError('<requests.
packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0302D8F0>: Faile
d to establish a new connection: [Errno 11004] getaddrinfo failed',))
None
udemy_dl returned -1
```

**Comment by nishad** [comment]
Check if any firewall blocks network access for `udemy-dl.exe`. Usually `Errno 11004` means DNS query is failed for the specific domain. So it may be a problem with your DNS server as well.

**Comment by anupammajhi** [comment]
Indeed it was a firewall issue, using proxy solved the issue.
