### ISSUE TITLE
[ERROR-1198] Traceback (most recent call last):

### ISSUE THREAD

**Issue by sofiane37** [nishad/udemy-dl-windows#110]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION]..

Replace everything between stars with current version of your udemy-dl.exe (output of udemy-dl.exe -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [x] I have never used the project.
- [x] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [x] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

I have this error : 

`[INFO-881] Downloading to: C:\udemy-dl-win\Learning_Python_for_Data_Analysis_and_Visualization

[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: logo.jpg
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 886, in <module>
  File "<string>", line 883, in main
  File "<string>", line 702, in udemy_dl
  File "<string>", line 379, in get_data_links
KeyError: u'results'
None
udemy_dl returned -1`

Thanks for help

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
