### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by mronline** [nishad/udemy-dl-windows#12]
![udemy](https://cloud.githubusercontent.com/assets/7905030/10423695/aba0a7ce-70d1-11e5-8e8b-0816273f7e89.png)

**Comment by nishad** [comment]
Please follow this. https://github.com/nishad/udemy-dl-windows/issues/5#issuecomment-137988471

**Comment by SamiDa** [comment]
I'm sorry but it's downloading something else not the Udemy course link i wrote to it.

**Comment by nishad** [comment]
I didn't get, what you meant.

**Comment by nishad** [comment]
It seems like this tool is not working for you, please stop using this tool and try to find any other alternatives.
