### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by vcazan** [nishad/udemy-dl-windows#127]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION]..

Replace everything between stars with current version of your udemy-dl.exe (output of udemy-dl.exe -v):  
Version : **2.1.2**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [x] I have used the project briefly.
---
I am trying to download a course but am getting this error. It looks like the output file is too long. Any fix?

[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 745, in udemy_dl
  File "<string>", line 663, in get_data
  File "<string>", line 538, in get_attached_file
  File "<string>", line 504, in mkdir
  File "os.py", line 157, in makedirs
WindowsError: [Error 206] The filename or extension is too long: u'.\\attached_files\\010 Utilizing the Mouse for More Efficient Models Control and Creation'
None
udemy_dl returned -1

**Comment by vcazan** [comment]
This is the project: 
https://www.udemy.com/solidwokrs-go-from-nothing-to-certified-associate-level

**Comment by vcazan** [comment]
Solved by changing the output to C:

**Comment by technoken** [comment]
@vcazan how did you solved this problem? i'm currently facing this issue.

**Comment by Jhony33** [comment]
How do you fix this problem? I have same problem please help me. Still same error after changing output to C: and adding --safe-file-names parameter :(
