### ISSUE TITLE
[BUG] Update.cmd - invalid file name used to replace existing file with new for aria2c

### ISSUE THREAD

**Issue by ValeriySh** [nishad/udemy-dl-windows#130]
https://github.com/nishad/udemy-dl-windows/blob/master/dist/update.cmd#L25
> ren aria2c.exe.new **udemy-dl.exe**

Should be 

> ren aria2c.exe.new **aria2c.exe**

**Comment by nishad** [comment]
Fixed with https://github.com/nishad/udemy-dl-windows/commit/8d4558ea930ec5e143d76a53aca751d9b511ab2d. Cheers !!!
