### ISSUE TITLE
Unable to download 

### ISSUE THREAD

**Issue by TanejaParvesh** [nishad/udemy-dl-windows#14]
Could not Download the course for offline usage
![fork2](https://cloud.githubusercontent.com/assets/14858304/10560658/6bc0dd60-752f-11e5-9707-c12c0e409f1c.jpg)

**Comment by nishad** [comment]
Please see this comment, there's an alternative version of the exe. Please use that.
https://github.com/nishad/udemy-dl-windows/issues/5#issuecomment-137988471

**Comment by TanejaParvesh** [comment]
Thanks @nishad
