### ISSUE TITLE
[BUG] [CRITICAL-261] Skipped. Expected quality not found!

### ISSUE THREAD

**Issue by Jekso** [nishad/udemy-dl-windows#154]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION]..

Replace everything between stars with current version of your udemy-dl.exe (output of udemy-dl.exe -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [X] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

I tried every thing but gives the same error [CRITICAL-261] Skipped. Expected quality not found!

**Comment by SamuelM333** [comment]
I have the same problem.

**Comment by vcazan** [comment]
Having the same issue....

**Comment by tofanelli** [comment]
same here

**Comment by SamuelM333** [comment]
This is a bug related to the Python version itself. Here's a relevant [issue](https://github.com/nishad/udemy-dl/pull/209#issuecomment-295298390).

**Comment by networking4sk** [comment]
same problem

**Comment by MHacker9404** [comment]
Same problem

**Comment by mahmoud-eskandari** [comment]
I have the same problem.

**Comment by MHacker9404** [comment]
I think my issue may be a result of the course not available for download.  Sent a request for it to be made available.

**Comment by henriquebaguiar** [comment]
@SamuelM333 Witch version do you use?

**Comment by SamuelM333** [comment]
I used a fork from someone else. Here:

`pip install -U git+https://github.com/smeggingsmegger/udemy-dl.git@master`

Again, here's the [issue](https://github.com/nishad/udemy-dl/pull/209#issuecomment-295298390).

**Comment by nishad** [comment]
Fixed with v2.1.3 (https://github.com/nishad/udemy-dl-windows/releases/tag/v2.1.3)
