### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by LucasRoot** [nishad/udemy-dl-windows#16]
Can how can I compile the code by myself?
I did some changes

**Comment by LucasRoot** [comment]
Don`t need anymore, thanks

**Comment by nishad** [comment]
If your changes are useful for others, you can create a pull request.

**Comment by DruhBoruch** [comment]
I have a problem with your script. Do you plan a new release ?

**Comment by LucasRoot** [comment]
Dont have the need.
Its just useful for me

**Comment by nishad** [comment]
@DruhBoruch, what is your problem ?
