### ISSUE TITLE
Error special characters?

### ISSUE THREAD

**Issue by SuppaDoppa** [nishad/udemy-dl-windows#17]
Hi Nishad, 

Can't download special char ( small dash ) with this software. 
For example if a title contains this char: it produces this error: 

``` Traceback (most recent call last):
  File "<string>", line 288, in <module>
  File "<string>", line 284, in main
  File "<string>", line 215, in udemy_dl
  File "<string>", line 172, in get_video_links
  File "C:\Users\Nishad\Desktop\udemy-dl\build\udemy-dl\out00-PYZ.pyz\encodings.cp850", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2013' in position 38: character maps to <undefined> ```

It errors on the small dash - .. looks like a normal dash but smaller... :(...
Look at this pic, just like that:
![capture](https://cloud.githubusercontent.com/assets/15558043/10870269/d422f62a-80c6-11e5-837f-5d5f34ecc743.PNG)


Can you please fix it so it accepts all chars possible, incl. this special dash? 
Tried the solution in closed issues (download only udemy-dl.exe en use that) but still same issue!?

TiA!

**Comment by nishad** [comment]
Issue #5 is the only one, I tried to fix so far. Unfortunately I don't have acces to courses with such title to try this out.

Could you try downloading after deleting aria2c.exe and curl.exe from the original release ?

**Comment by SuppaDoppa** [comment]
Hi Nishad, thanks for you answer! I hope you are doing well. 
I already did remove those 2 files; I just tried it with file udemy-dl.exe. But still no success. 

I just tried to download the preview lecture of this course: https://www.udemy.com/arabic-a21/
and it goes wrong. Just try it, as you don't need access for preview lectures, you will notice. 
But if you want a free course with such problem, i will try and find one. Please let me know first if you can download this one. Thank you very much for putting your spare time in this project! Appreciate it. 

Regards!

**Comment by nishad** [comment]
@SuppaDoppa, could you resolve this issue or did you find any alternative solution ?

**Comment by SuppaDoppa** [comment]
Tried another course with free enrollment and same chars, and there it worked!!!... :)
so i guess it works only when you are enrolled in a course!
If not enrolled it will not work!

**Comment by nishad** [comment]
Thanks for the input, feel free to reopen this issue if this error persists.
