### ISSUE TITLE
[PROPOSAL] Request

### ISSUE THREAD

**Issue by Chlitzxer** [nishad/udemy-dl-windows#18]
I first thanks for sharing such an excellent tool, I have a request I am using the solo .exe that is up to date the alpha version that you share on a link that is not on github yet, I have multiple paid courses that are very very long and most of them have pdf, .txt and .zip files, is there any way the script can be modify to pull also those files? Is really annoying go thru every link searching for attached files, if you can do it I really appreciate your help! Please also update the source code of the .exe alpha version is not up to date :(

**Comment by nishad** [comment]
Alpha version is a dirty fix for some problems related to special characters. It's a stripped version of the original version without any external downloader support. It was provided for some users with specific problems. Those fixes are so dirty to be pulled into the original version. Soon there will be a new release with all there fixes included.

As the description says the only intention of this tool is to be a a windows utility to download videos from udemy for personal offline use.

There is no plan to extend this tool to be something for making complete copies of udemy courses. Please feel free to fork it and make own changes.

**Comment by Chlitzxer** [comment]
I wish I know how to do it but I don't really know can you help with a piece of code on how to call some other file names? thanks!

**Comment by nishad** [comment]
This was discussed before, please check this thread, there's a proposed solution from coursera-dl
https://github.com/nishad/udemy-dl-windows/issues/4
