### ISSUE TITLE
Revocation Error

### ISSUE THREAD

**Issue by d4me94** [nishad/udemy-dl-windows#19]
Hello Sir,
               First Of All Thank You For Making Such An Amazing Script Which Made Downloading Videos From Udemy Very Easy. I was using this script from last 2-3 months and it was running flawlessly without an error but from yesterday, I am facing an error. Nothing changed on my laptop but automatically this error started to come. Below Are The Details Of Error:::

![udemy](https://cloud.githubusercontent.com/assets/15673909/10974159/b3283e7e-8406-11e5-8dc3-8bea2a6c71b1.jpg)

11/05 21:28:45 [ERROR] CUID#6 - Download aborted. URI=https://udemy-assets-on-demand.udemy.com/2015-05-29_13-39-04-dbb5af81dba269934615098c3b796e4a/We
bHD_720p.mp4?nva=20151105195558&token=0a92d1c88b1be361bcbb2
Exception: [AbstractCommand.cc:350] errorCode=1 URI=https://udemy-assets-on-demand.udemy.com/2015-05-29_13-39-04-dbb5af81dba269934615098c3b796e4a/WebH
D_720p.mp4?nva=20151105195558&token=0a92d1c88b1be361bcbb2
  -> [SocketCore.cc:975] errorCode=1 SSL/TLS handshake failure: Error: The revocation function was unable to check revocation because the revocation server was offline.
(80092013)

**Comment by nishad** [comment]
Seems like something wrong with udemy. Could you try after deleting aria2c.exe. And if that fails try after deleting curl.exe

**Comment by d4me94** [comment]
Okay Sir, It is working fine now after deleting aria2c.exe. but now interface has changed, Now downloading interface had gone very basic like Youtube-dl interface..please update this problem if you can.

**Comment by d4me94** [comment]
By the way Thank you for your help and time to heal this problem thank you.

**Comment by nishad** [comment]
I'll wait till the issue is reported from multiple users. I am planning to make external downloaders optional to avoid such problems. It's known that different downloaders behave different ways and I'll be adding only new binaries of them if available from their own developers.

**Comment by Ryan147** [comment]
Today I wanted to download a course and it also gives the error "Cannot download lecture ...."

**Comment by nishad** [comment]
Usually this happens when you try to download a course you are not enrolled in. So make sure you are enrolled in the course via your browser.

**Comment by Ryan147** [comment]
Yes somehow it is working again.
