### ISSUE TITLE
Can not download lecture

### ISSUE THREAD

**Issue by rinodung** [nishad/udemy-dl-windows#2]
I tried to download a premium course and get this error: https://www.udemy.com/ios-8-and-swift-how-to-make-a-freaking-iphone-app/

Can you help me to show this problem?
![cannot download lecture](https://cloud.githubusercontent.com/assets/7805715/9299717/eb170cb4-44e8-11e5-8e33-13e04a4cee76.png)

**Comment by nishad** [comment]
Usually this happens when you try to download a course you are not enrolled in. So make sure you are enrolled in the course.
