### ISSUE TITLE
for help

### ISSUE THREAD

**Issue by rockiraman** [nishad/udemy-dl-windows#20]
I am new in github.please tell me how to use this script in windows?  
Thanks in advance

**Comment by nishad** [comment]
This is a command line tool, so use it via command prompt or power shell.

**Comment by rockiraman** [comment]
i just have downloaded udeny-dl for winsows.is i need to install any other thing or just enter command 
demy-dl.exe https://www.udemy.com/COURSE_NAME

**Comment by nishad** [comment]
You only need to enter the command from the folder of udemy-dl.exe via command prompt

**Comment by rockiraman** [comment]
i opened cmd from udemy-dl but it is saying udemy-dl is not a recognised command

**Comment by rockiraman** [comment]
please help me

**Comment by rockiraman** [comment]
please make a short video to solve all doubts

**Comment by nishad** [comment]
It seems like this tool is not working for you, please stop using this tool and try to find any other alternatives.

**Comment by rockiraman** [comment]
i execute the comands but it shows connot download from........course name 
everytime it is showing like this

**Comment by nishad** [comment]
May be this tool is broken. I'm not so sure. Or there's a bug with it.

**Comment by rockiraman** [comment]
i hope you will solve it shortly i appreciate ur work

**Comment by nishad** [comment]
If it is not reported from multiple users, I'll ignore. And if there are many Similar issues I'll deal with it. Just now I ran my tests, and it worked well. Seems like it's not working only for you. Thanks for giving it a try. All the best for finding an alternative solution.

**Comment by rockiraman** [comment]
thanks nishad

**Comment by nishad** [comment]
Btw, what's the command you are executing to get this 'Cannot download from ...' Error ?

**Comment by rockiraman** [comment]
udemy-dl.exe https://www.udemy.com/plc-programming-from-scratch/

**Comment by rockiraman** [comment]
Then user name and password

**Comment by rockiraman** [comment]
Then I get mentioned errors

**Comment by nishad** [comment]
Are you getting the same error of this issue ?
https://github.com/nishad/udemy-dl-windows/issues/2

**Comment by rockiraman** [comment]
Yes

**Comment by nishad** [comment]
Usually this happens when you try to download a course you are not enrolled in. So make sure you are enrolled in the course via your browser.

**Comment by rockiraman** [comment]
Can I enroll paid courses without paying anything?

**Comment by nishad** [comment]
This tool is not intended to infringe any copyrights of udemy. As the project's description , this will only help to get videos for personal offline use. Mainly due to bandwidth limitations of users from many developing countries. Please pay for the courses and respect udemy's business model.

**Comment by rockiraman** [comment]
OK sir
