### ISSUE TITLE
Re-Enter Udemy password

### ISSUE THREAD

**Issue by Raphael25** [nishad/udemy-dl-windows#21]
Hi,

I don't have a problem with this program (anymore) as I think I managed to fix the one I was having (or this could just be a coincidence but I thought I would share it anyway).

I was having an issue getting this program to download any videos for me.  I was enrolled in the course I was trying to download but it just kept saying the following.

<div class="box-footer">
            Don't have an account?
            <a class="sign-link" href="/join/signup-popup/?displayType=ajax&amp;locale=en_US&amp;display_type=popup&amp;next=https://www.udemy.com/&amp;returnUrlAfterLogin=https://www.udemy.com/&amp;showSkipButton=1" data-purpose="sign-up">
               Sign up
            </a>
        </div>

What I did though to get it working was, through a webbrowser, I went into the 'Account' section within 'Edit Profile' in Udemy and I reentered my password.  I sign into Udemy using my Google account and I just re-entered my password from the google account.

Then after doing this, Udemy-dl-exe worked first go, it downloaded the courses without an issue.

Perhaps this is an issue with people who sign into Udemy using an google account (or facebook), or yeah perhaps it was just a coincidence.

Maybe this will help others.

Cheers
Raph

**Comment by nishad** [comment]
@Raphael25 could you add this tutorial to project wiki here https://github.com/nishad/udemy-dl-windows/wiki

Closing this thread to prevent novice users add different issues here. A little bit of housekeeping. ;)
