### ISSUE TITLE
Cannot download lecture error and downloading wrong lecture later

### ISSUE THREAD

**Issue by samvid1992** [nishad/udemy-dl-windows#22]
I am trying to download [this lecture](https://www.udemy.com/make-mobile-games-like-a-pro-using-unity-game-engine/) . i have paid for it as well. Instead it udemy-dl is giving me "cannot download lecture" error and then download different lecture [this one](https://www.udemy.com/create-a-2d-platformer-game-with-unity/).

 I did download latest version of udemy-dl from [this site](https://github.com/nishad/udemy-dl-windows/releases/tag/v1.8.0)

here are screenshots. I have hidden username and password. 
![screenshot 40](https://cloud.githubusercontent.com/assets/1859203/11055113/9cac3a4c-8799-11e5-86ee-bfcd3345e279.png)
![screenshot 41](https://cloud.githubusercontent.com/assets/1859203/11055116/a30f0202-8799-11e5-936c-1669bfe40f4b.png)

**Comment by nishad** [comment]
Usually this happens when you try to download a course you are not enrolled in. So make sure you are enrolled in the course via your browser.

**Comment by samvid1992** [comment]
I was enrolled in the course, but error was about something else. i did manage to make it run by deleting Aria2c.exe and curl.exe.

**Comment by jendmaoul** [comment]
Haha... this is also happen to me :D

**Comment by med-ahmed** [comment]
cannot download lecture help me please

**Comment by nishad** [comment]
@med-ahmed, let me know the exact error, showing up.

**Comment by med-ahmed** [comment]
hy dear nishad 
I am trying to download this cours https://www.udemy.com/if-you-can-cook-you-can-code/?couponCode=CBMONDAY15
 udemy-dl is giving me "cannot download lecture" error I have hidden username and password. 
![sans titre](https://cloud.githubusercontent.com/assets/16116935/11535943/16f82a92-990e-11e5-8ae0-2f66bc6ccbf5.png)

**Comment by med-ahmed** [comment]
Do I have to pay  to download it

**Comment by jendmaoul** [comment]
LOL of course you got error like that, because that course is paid course and you didn't bought it yet.

**Comment by joyb81** [comment]
How to Fix this - How we can access it - all contents?

**Comment by nishad** [comment]
@joyb81 its is not a bug. As explained by @jendmaoul in https://github.com/nishad/udemy-dl-windows/issues/22#issuecomment-161688907, if you are trying to download a course you are not enrolled  in will download only preview lectures. Make sure you are enrolled in the course via your browser.

**Comment by joyb81** [comment]
Having issues for both versions - also let me know  if you share script that work for all - ready to pay for it

**Comment by nishad** [comment]
What do you mean by both versions ? The script works for all.

**Comment by joyb81** [comment]
Course which i have enrolled they are also not able to download all
lectures - they downloads two or 3 videos of a sections and lets say a
course has 10 section then it goes up to 6 and download limited videos.

I have tried for enrolled course and also not enrolled courses results is
same

On Thu, Dec 24, 2015 at 8:16 PM, Nishad TR <notifications@github.com> wrote:

> What do you mean by both versions ? The script works for all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nishad/udemy-dl-windows/issues/22#issuecomment-167119929>
> .
>



-- 

*Warm Regards*

*Joy Banerjee*



*IT (Consultant) *

 Cell +91-8447298600

Email: *joybanerjee@aikitsupport.com* <joybanerjee@aikitsupport.com>

*Services  *
IT Consultancy, WEB Hosting, WEB Development, Remote Support
www.aikitsupport.com

*_____________________________________________________*

*AIK IT Support*

*_____________________________________________________*

*Consider the environment before printing this email!*

**Comment by nishad** [comment]
May be this tool is not working for you. Please try some other alternative solutions. Seems like it is broken, and I'm busy enough to fix it.

**Comment by joyb81** [comment]
if you want convert this to a paid project - i can buy if you want work with me - let me know thanks email me joybanerjee@aikitsupport.com and we can take this further

**Comment by nishad** [comment]
@joyb81 This is open source project, and it will remain free forever.  The soul purpose of this project is to help users with poor connectivity in downloading videos from udemy for personal offline use.

**Comment by jendmaoul** [comment]
@joyb81 this tool still work for me for both version free and paid version, and of course if it's paid video you have to buy it first. I know what you mean man, if you want to buy udemy ripper there is black market in the internet group that sell for it not this tool this tool is open source project.

**Comment by bharken** [comment]
I had this problem just now. Tried it on all my paid courses but still getting this error "Cannot download this lecture".

This is what I get in the end:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 110, in get_video_links
    video_url = parse_video_url(lecture_id, hd)
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 74, in parse_video_url
    re.MULTILINE | re.DOTALL).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Scripts\udemy-dl.py", line 5, in <module>
    main()
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 229, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, output_dir)
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 160, in udemy_dl
    for video in get_video_links(course_id, lecture_start, lecture_end, hd=True):
  File "C:\Python34\lib\site-packages\udemy_dl\udemy_dl.py", line 117, in get_video_links
    print('Cannot download lecture "%s"' % (lecture))
  File "C:\Python34\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position 41: character maps to <undefined>

**Comment by AnkiPatel** [comment]
I am facing same problem. I have already enrolled the course and able to see on web-page but not able to download. Please help here.

**Comment by lestex** [comment]
Faced same problem with course I bought about week ago and with course been just bought

**Comment by reza147** [comment]
Hi . I use udemy-dl . when udemy-dl start to download course from udemy i see that udemy-dl could not download completely video of course from udemy . please help me and tell me what should i do for download completely ? please see
![untitled](https://cloud.githubusercontent.com/assets/17479605/13330534/73e4c394-dc0e-11e5-9d75-e4e7f5affa52.png)
 my screenshot :

**Comment by tobias-p** [comment]
reza, when you open your eyes and try to read the infos the command line is giving you, then you could get the following infos after the line of "=" that you 
1. downloaded 8.8 MiB of totally 58MiB (8.8MiB/58MiB (15%) with a 
2. Downloadspeed (DL) of 163 KiB and 
3. an Estimated Time (ETA) of 5 minutes and 12 seconds....

I cant see there that there's an error or something like that.

**Comment by reza147** [comment]
Hi tobias-p . Thanks a lot for your answer . okay now what should i do that solve this problem ? 
please guide me step by step if possible . really i need your help .

**Comment by tobias-p** [comment]
Well, what you see is no problem, it's just an info how far you downloaded the file. You just have to wait until the ETA is 0, then your file is finished downloading and udemy-dl goes to the next ;)

**Comment by tobias-p** [comment]
If you want to download several courses, you could also run a .bat file on windows.

you could use following line for your .bat file:

`udemy-dl.exe -u koroshkabir710@yahoo.com -p yourpasswordhere -o "C:\Path\to\Course" --lecture-start 1 https://www.udemy.com/Path-of-Course/`

"Path\to\Course" is where you want your course downloaded. I have it at "C:\Learnvids\Udemy\CourseName" where CourseName is the Name of the course (because I have to download about 50 courses ^^.

--lecture-start 1 is just there because I sometimes have to stop downloading. When I then restart, i can raise the lecture-start to ne number which i have to download now.

And the last is the http to your course. 

Your .bat file could look like this:

`udemy-dl.exe -u koroshkabir710@yahoo.com -p yourpasswordhere -o "C:\Learnvids\Udemy\Course 1" --lecture-start 1 https://www.udemy.com/course_1/
udemy-dl.exe -u koroshkabir710@yahoo.com -p yourpasswordhere -o "C:\Learnvids\Udemy\how-to-learn" --lecture-start 1 https://www.udemy.com/how-to-learn/`

Hope this helps ;)

**Comment by reza147** [comment]
Hi dear tobias-p . thanks a lot for your guide . very good . thank you  . 
i hope you have a nice time .

**Comment by nishad** [comment]
Invalid, but useful thread. @tobias-p, you can contribute to the project wiki here https://github.com/nishad/udemy-dl-windows/wiki. That may help future novice users.

Closing this thread as a pert of routine housekeeping.

**Comment by reza147** [comment]
Hi . How can i find subtitle for udemy courses ?

**Comment by reza147** [comment]
Hi . I have a problem please help me . when i want download from udemy i choose a course and click on it and then i click on Start Free Preview  and again i do this work that mean i click on Start Free Preview and i see a link i copy this link and paste in udemy-dl for for download . to day when i want download a course from udemy with this method i see this error : 
![s](https://cloud.githubusercontent.com/assets/17479605/13745401/0cbf2634-ea03-11e5-9576-4f7423d76c91.png)
and now i do not have a any link for download . please help me . 
Thank you .

**Comment by nishad** [comment]
This thread is closed, and your problem is different, open a new issue.

**Comment by reza147** [comment]
Thanks a lot for your response . But i test with another system and i see this problem . 
please tell me . How can i bring a link for use in udemy-dl ?

**Comment by nishad** [comment]
This thread is closed, and your problem is different, open a new issue.

**Comment by reza147** [comment]
excuse me what do you mean that you say open a new issue ?
Thank you .

**Comment by jendmaoul** [comment]
@reza147  do you understand english? create new issue on this github, thank you, and if you won't get that udemy result buy or enrolled course not free priview.

**Comment by reza147** [comment]
Thank you dear jendmaoul . No . i can not understand English very well . 
see this is my error : javascipt:void%280%29
I try with another system but again i see this erroe :javascipt:void%280%29

**Comment by reza147** [comment]
Please give me a video about use to udemy-dl .
really i need it .
