### ISSUE TITLE
Can you make it download text,quizzes or picture?

### ISSUE THREAD

**Issue by Saufy00** [nishad/udemy-dl-windows#26]
It would be great if you can add those features. The program downloading videos itself already dope. If  you add more , it will be far greater. I'm just suggesting ehe Thanks

**Comment by nishad** [comment]
@Saufy00,
Its answered before, please see the response for https://github.com/nishad/udemy-dl-windows/issues/10

**Comment by mukhlesur-millon** [comment]
could you please comment here the course link which has picture?

**Comment by mouradxmt** [comment]
Please can you add this features !

**Comment by nishad** [comment]
Answered here https://github.com/nishad/udemy-dl-windows/issues/67
