### ISSUE TITLE
Error in downloading.Please take a look.

### ISSUE THREAD

**Issue by Saufy00** [nishad/udemy-dl-windows#29]
![screenshot_37](https://cloud.githubusercontent.com/assets/16362187/11999745/703f2ebc-ab00-11e5-9839-90f4067f6ee7.png)
How do I resume the download? I dont understand.Thanks.

**Comment by nishad** [comment]
From this screenshot, I'm unable to rectify the error. Usually, aria2 will continue the broken download once you try to download the same course again. However, you can delete `aria2c.exe` to download with curl. You can delete both `aria2c.exe` and `curl.exe` to try downloading with the built-in downloader, that will work in most of the cases.

**Comment by Saufy00** [comment]
Oh. Thanks for the reply! I'll try it and tell you the result later.
