### ISSUE TITLE
Udemy-dl taken down, now what?

### ISSUE THREAD

**Issue by madmax2** [nishad/udemy-dl-windows#3]
Will this project and Udemy-dl  be moved to another repository?

**Comment by nishad** [comment]
@madmax2, I believe that this  repository (Probably other than the logo, and the name udemy) doesn't violates any udemy copyrights, as they declared in https://github.com/github/dmca/blob/master/2015-08-12-Udemy.md. I'll be keeping it available. However there is another `udemy-dl` repository which still supports pip, but in different way. https://github.com/nishad/udemy-dl
