### ISSUE TITLE
cannot download because bcrypt.dll not found

### ISSUE THREAD

**Issue by webdev20** [nishad/udemy-dl-windows#30]
bcrypt.dll is not for windows xp, so I think this shouldn't be mentioned to support windows xp, unless that problem is fixed.

Thanks in advance,
Ari

**Comment by nishad** [comment]
udemy-dl.exe is tested and works with Windows XP service pack 3. Bcrypt.dll is a dependency of aria2c.exe. You can delete aria2c.exe, to use curl. You can even delete both aria2c.exe and curl.exe to work with built in downloader. 

This is explained in https://github.com/nishad/udemy-dl-windows/blob/master/README.md under the heading of downloader.
