### ISSUE TITLE
Cant download any lectures

### ISSUE THREAD

**Issue by n810** [nishad/udemy-dl-windows#32]
Hi.

Just started using this script and had no problems to begin with. 

Now for the last few days every time I try I get the error below.

![image](https://cloud.githubusercontent.com/assets/2323803/12028775/1a19949e-ae31-11e5-88e8-5c59b07d6a57.png)

Being one who dabbles in Python I did a little poking around and I think there has been a change to Udemy.

In the function patse_video_url  the embed_url string for the above example becomes https://www.udemy.com/embed/3357616/   this URL takes me to a page - Seems like we're a bit lost."

![image](https://cloud.githubusercontent.com/assets/2323803/12028824/eca76756-ae31-11e5-8389-07e5b70906e1.png)

Im guessing they have changed the URL structure. 

This is as far as I can take it. IF im right can you please fix this ? :)

**Comment by bharken** [comment]
Also had this problem just today - [my comment from another thread] (https://github.com/nishad/udemy-dl-windows/issues/22#issuecomment-167699263)
Few hours before, my download was ongoing and I left my PC. But then after a few lectures, it stopped. So I tried starting it again and now I get those error messages too. I tried it on all my paid courses but no luck. Please help.

**Comment by noph34r** [comment]
yeah, this is a problem
just download yesterday, it was okay and then i go to sleep
but when i check today, none is downloaded...

**Comment by Sulduzlu** [comment]
Cannot download lecture Sir!?!
 Download links are changed! (I think)
 Before links downloads from Akamai like this Link: https://sknowbucket-a.akamaihd.net/2013-10-14_22-29-09-e1ece5d5151c24417daad579e350187e/WebHD_720p.mp4?__gda__=1405633330_e07dde57e3243969ac58e9e45f6b5f4d&filedownload=attachment
 But now links download from udemy like this link : https://udemy-assets-on-demand.udemy.com/2015-08-22_17-11-54-e2ea85b3d0ff78c8446b7fde92e9e6cd/WebHD_720p.mp4?nva=20151229160132&token=0b2af792531b7f7c19be6
 Changed from yesterday (I think)
 Please Check & update your GOOD tool SIR , we wait for your UPDATE
 Thanks for your attention.

**Comment by jaan143** [comment]
Udemy is updated his site so i think this is the reason that this method is not working now
plz Sir do update this software also we really need that
thanks very very much

**Comment by webdev20** [comment]
Same problem here!

**Comment by adadeacon** [comment]
Got the same problem. Currently using "Video Download Capture" to download courses, but it is so tedious because you have to enter every single video url separately and you can only download a few per hour.
Would love an update for udemy-dl.exe

**Comment by luiz-rocha** [comment]
Tip: youtube-dl https://www.udemy.com/........../learn/ -o 'videos_downloads/%(autonumber)s-%(title)s.%(ext)s' -u your@email.here -p your_password_here

**Comment by bharken** [comment]
@luiz-rocha You used youtube-dl and it worked? Is that the command?

**Comment by luiz-rocha** [comment]
Yes, download or update the youtube-dl them use the command above.
I'm downloading right now.

**Comment by bharken** [comment]
So am I. --lecture-start and --lecture-end won't work though.

**Comment by luiz-rocha** [comment]
here try this 
-o 'videos_download/%(playlist_index)s-%(title)s.%(ext)s'

use --playlist-start  --playlist-end

**Comment by bharken** [comment]
>use --playlist-start --playlist-end

This one works. Thanks again!

For the output directory, no need to put them inside single quotes.

**Comment by nguoichuadangki** [comment]
Thanks. I got it

**Comment by raouf30** [comment]
are you guys able to download videos now with this code?

**Comment by nguoichuadangki** [comment]
youtube-dl https://www.udemy.com/........../learn/ -o 'videos_downloads/%(playlist_index)s-%(title)s.%(ext)s' -u your@email.here -p your_password_here. I can download with this code :D

**Comment by luiz-rocha** [comment]
If you guys use linux or know how to use python,
I've made a python3 script to automate:
http://pastebin.com/kBnshV8j

**Comment by bharken** [comment]
@luiz-rocha Great! How about udemy-dl, can you update it?

**Comment by n810** [comment]
Im finding YouTube-dl to work very well as described here. 

I've changed the output switch to better name the files and put them in a folder. All the options are shown on the website and documentation of the program.  

Additionally there is a gUi available that I have found works well if your so inclined. 

https://github.com/MrS0m30n3/youtube-dl-gui

**Comment by adadeacon** [comment]
This worked for me to download Udemy courses:
youtube-dl.exe --playlist-start 1 --playlist-end 100 -o videos_downloads/%(playlist_index)s-%(title)s.%(ext)s -u USERNAME-p PASSWORD https://www.udemy.com/.../learn/

**Comment by PJCSantos** [comment]
@n810 How can I set that program to separate files from different sections by folders? Btw thanks for sharing, works like a charm!

**Comment by n810** [comment]
Hi .

Im not sure if you can get the videos into folders based on the sections in
the course.
Looking at the commands for youtube-dl nothing jumps out at me.

I am numbering mine based on the position in the course (not a just a
sequential number) so I just sort them.

My exact command line is:

youtube-dl https://www.udemy.com/COURSE_TITLE/learn/ -o
%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s -u YOUR_USERNAME -p
YOUR_PASSWORD

Obviously replace the course, username and password as appropriate.

**Comment by luiz-rocha** [comment]
Me again :), for who want to put files in separated folders.

This is the command:

youtube-dl https://www.udemy.com/........../learn/ -o 'videos_downloads/%(chapter_number)s-%(chapter)s/%(playlist_index)s-%(title)s.%(ext)s' -u your@email.here -p your_password_here

This isn't  on manpages or docs, I guess.

See this for more information:

https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/udemy.py

**Comment by luiz-rocha** [comment]
And for last

If you want to know all options for current video download append --write-info-json to the command

The best command I reach is that:

```bash
youtube-dl https://www.udemy.com/......../learn/ -o '%(playlist_title)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s-%(title)s.%(ext)s' -u your@email.here -p your_password_here
```
The python script
http://pastebin.com/fPCCJ0Wg

And good learning for all ;)

**Comment by hiennguyen82** [comment]
PLEASE FUCKING STOP SPAM ME.

2016-01-11 22:44 GMT+07:00 Luiz Augusto Rocha <notifications@github.com>:

**Comment by bharken** [comment]
@luiz-rocha That's a lot better! Thanks a lot! Can you also update the udemy-dl?

**Comment by AnkiPatel** [comment]
Hi Team,
I think i am doing something stupid. I have Udemy-dl-windows.1.8.0. Now i am using youtube-dl.exe with following command

youtube-dl https://www.udemy.com/<MY enrolled course link>/learn/ --playlist-start 1 --playlist-end 10 -o 'videos_downloads/%(chapter_number)s-%(chapter)s/%(playlist_index)s-%(title)s.%(ext)s' -u ankita@myid.com -p mypsw

It is creating file "(title)s.(ext)s'.part" under 'videos_downloads\(chapter)s folder and keep overwriting it. Please correct me.

**Comment by luiz-rocha** [comment]
Ok

First you need download the latest youtube-dl:
https://yt-dl.org/latest/youtube-dl.exe

Them remove the single quotes, like @bharken already said.

**Comment by denis-n** [comment]
Question to luiz-rocha - can youtube-dl download audio too?
I found a course which contains audio lessons. 

How can I download them?

**Comment by luiz-rocha** [comment]
You have to see if there are audio formats available
I've tried with the option -F, but showed me only videos
```
format code  extension  resolution note
360p         mp4        360p       
720p         mp4        720p       (best)
```

**Comment by Rizwanjamal** [comment]
can I use this youtube-dl command for the premium courses in which i m not enrolled. ??

**Comment by denis-n** [comment]
I guess you are not allowed to do so.

**Comment by nishad** [comment]
Fixed in **v2.0.1**. You can download the latest release from here https://github.com/nishad/udemy-dl-windows/releases/latest

**Comment by Rizwanjamal** [comment]
thanks nishad :)

**Comment by buccolik** [comment]
Hello,

How can we download the other course files like .pdf, .txt ...

Thank you.
