### ISSUE TITLE
Can not Download Lecture XXX same as Udemy Ripper

### ISSUE THREAD

**Issue by cloud4bpm** [nishad/udemy-dl-windows#33]
As with Udemy Ripper, suddenly seems to be banned all accounts using this rippers. Because all rippers give us the same error: Can not download Lecture XXXXXXX.

I was trying to download using the www.udemy.com/gift/course-name and it results well until this morning.

Maybe is a security reason from this course business.

**Comment by nishad** [comment]
What do you mean by ripper? It's a repository of udemy-dl windows version.

**Comment by timrijckaert** [comment]
It's not working anymore same issue here.

**Comment by nishad** [comment]
Have you tried the latest release 2.0.1 ? It's available here.
https://github.com/nishad/udemy-dl-windows/releases/tag/v2.0.1
