### ISSUE TITLE
[BUG] Error trying to download a video from enrolled course with new v2.0.1 Udemy-DL?

### ISSUE THREAD

**Issue by SuppaDoppa** [nishad/udemy-dl-windows#37]
Hi Nishad, 

I got this error: 
![capture](https://cloud.githubusercontent.com/assets/15558043/12406383/a8fd5cba-be4c-11e5-9314-5100c9e9c907.PNG)

What does it mean? :( 

Thanks for all your work! 
Regards,
S.D.

**Comment by nishad** [comment]
It says, the script failed to get a proper title for the Chapter.

**Comment by SuppaDoppa** [comment]
Why would this happen? 
The first lecture name is called: "Closed Captions/Sub Titles for the course" 
Maybe because of the "/" sign? Or no?

And is there any workaround you know that i could try maybe, Nishad or someone else? 
Thanks in advance!

**Comment by nishad** [comment]
Try using these options to skip the lectures in question, and see if there is any improvements.

``` 
--lecture-start LECTURE_START
                        Lecture to start at (default is 1)
--lecture-end LECTURE_END
                        Lecture to end at (default is last)
```

**Comment by SuppaDoppa** [comment]
Nishad, 

Thank you! 
That first didn't work after i skipped first lecture only. 
But after i skipped the new first added chapter (with 3 lectures in it) it worked!!! :) 

This is what i did: 
--lecture-start 4  --lecture-end XXX (=last lecture)

then it worked now! :100: 

But why did this happen?
Is it because of newly added chapter/stuff to an existing course maybe?
If you want more info to examine this, please let me know. But for now: thank you very much for the tips and your hard work, Nishad!!

**Comment by nishad** [comment]
I'm not so sure about the error. If there's more issues similar to this I'll investigate. However, there are plans for more options to easy debug or error logs by next major release.

**Comment by SuppaDoppa** [comment]
Wow! Cool.. can't wait for that release! :+1: 
Thanks Nishad!

And I'll certainly report if i come across more errors like this one.

**Comment by surajy** [comment]
\\
help me getting and error

while using this getting error give me solution please



​
​

**Comment by SuppaDoppa** [comment]
what error? screenshot? 
and please open a new thread if not same error as this one.

**Comment by surajy** [comment]
error in attachment please se the image

while typing udemy-dl.exe in cmd showing it does not recognizing in
 inexternal and external command

**Comment by SuppaDoppa** [comment]
i don't see attachment. please don't reply via email. 

and use new thread. not same bug as here ... as far as i can judge! 
and read here how to use this program via cmd: 
https://github.com/nishad/udemy-dl-windows#advanced-usage

**Comment by SuppaDoppa** [comment]
@Nishad: i think i found it why this error is occuring! Can you take a look at this please, whenever you have some time to spare? :) 

I had more lectures with same error in 2 different courses.
This error seems to happen when the first lectures don't have a "section".
See the attachments. 
Blue arrows mean from there no problem to download.
Red arrows mean it will throw the above error. 

![capture2](https://cloud.githubusercontent.com/assets/15558043/12432373/2a9695b2-befb-11e5-81b9-3e1a2b727035.PNG)

So you have to always skip the "sectionless" lectures... 
Can you confirm Nishad? TiA!

**Comment by keyloggerff** [comment]
![Uploading Screenshot_2016-01-23-19-06-38.png…]()
hello bro i am getting same error as shown in this pic 
as in this first case 
![tmpdoodle1453556436060](https://cloud.githubusercontent.com/assets/16852487/12530416/03163d3c-c205-11e5-8153-91542a03eeb5.jpg)

can you please tell me the all  commands please
thank you @nishad

**Comment by SiteDesignUSA** [comment]
Tonight I tried to download course (which I bought) and received 

Failed to get course ID

For one course

and

Traceback (most recent call last):
  File "<string>", line 374, in <module>
  File "<string>", line 370, in main
  File "<string>", line 294, in udemy_dl
AttributeError: 'NoneType' object has no attribute 'encode'

for another course.

**Comment by SiteDesignUSA** [comment]
Error
```
Failed to get course ID
```
From this course.

```
https://www.udemy.com/become-a-speeddemon-hack-automation-focus-efficiency-to-have-more-time/learn/#/
```
Doesn't go away if I use the --lecture-start and --lecture-end switches.

The error
```
Traceback (most recent call last):
  File "<string>", line 374, in <module>
  File "<string>", line 370, in main
  File "<string>", line 294, in udemy_dl
AttributeError: 'NoneType' object has no attribute 'encode'
```
went away from this course
```
https://www.udemy.com/7-comedic-habits-to-be-consistently-funnier-presenting/learn/#/
```
when I started the --lecture-start switch at the first lesson AFTER Section 1 (they had lessons before Section 1) 

AND --lecture-end <number of last lesson> switch.

**Comment by nishad** [comment]
Fixed with https://github.com/nishad/udemy-dl-windows/releases/tag/v2.1.1
