### ISSUE TITLE
.exe files closes as soon as i run it

### ISSUE THREAD

**Issue by sarthak-pandit** [nishad/udemy-dl-windows#38]
please help with this problem
as soon as i run udemy-dl.exe the box just opens and closes.

**Comment by nishad** [comment]
This is a command line tool, so use it via command prompt or power shell. Go to the folder of the executable in command prompt and in terminal prompt give this whole command modified with your credentials.

```
udemy-dl.exe -u user@domain.com -p $ecRe7w0rd https://www.udemy.com/COURSE_NAME
```

**Comment by sarthak-pandit** [comment]
thankyou for responding and really you are doing a mind blowing job 

using the windows tools and the python code give me this same problem
![nu](https://cloud.githubusercontent.com/assets/13116306/12449475/6b085590-bf32-11e5-9022-43364d1f775c.png)
 please help with it.
regards from
sarthak pandit

**Comment by nishad** [comment]
Please see this thread https://github.com/nishad/udemy-dl-windows/issues/20

**Comment by soamz** [comment]
I says, downloading to C:\xxxxx. 
But download isn't happening, I guess, as task manager shows 30Kbps. 

How do we check where is the download happening ?

**Comment by soamz** [comment]
Getting this error.

![12527938_10156577328120262_1709670933_n](https://cloud.githubusercontent.com/assets/2391697/13858506/fe93b4cc-eca4-11e5-8f11-812aa84fbf25.jpg)

**Comment by nishad** [comment]
You should select, some writable folder as output. `udemy-dl` doesn't got write permission to that folder. You can use `-o` to use any other output folder.

**Comment by soamz** [comment]
windows cmd screens shows me C:/users location, but I want to store under E location.
Now how do I select E location ?

**Comment by nishad** [comment]
`udemy-dl.exe -o "E:\"` will do that. Or you can copy all `udemy-dl-windows` binaries to **E:** and execute `youdemy-dl.exe` in  **E:** via command prompt.

Please refer https://github.com/nishad/udemy-dl-windows/blob/master/README.md#usage, for further assistance.

**Comment by soamz** [comment]
Worked worked! Awesome script.
