### ISSUE TITLE
I have tried several times but it shows is not valid windows application

### ISSUE THREAD

**Issue by Shimoli** [nishad/udemy-dl-windows#42]
I have tried several times but it shows is not valid windows application  http://imgur.com/enOkdHd

**Comment by warrendeleon** [comment]
Hello @Shimoli,

Is you terminal working directory in the same folder as the .exe? If not, open the folder where the program is, press SHIFT and right click, then you will see in the an option "open terminal here" or something similar. It will open a window cmd with working directory located on the application folder.

or you can use:
>`cd path\where\udemy-dl.exe\is\located`

After that you can user in the command:
> `udemy-dl.exe -u yourudemyemail -p yourpassword https://www.udemy.com/yourpaidcourse`

I hope that this can solve you problem.

**Comment by nishad** [comment]
Your `udemy-dl.exe` is corrupted. Make sure that you download these files **ONLY** from this repository. Latest release can be downloaded **ALWAYS** from https://github.com/nishad/udemy-dl-windows/releases/latest

Following are MD5 sums for the current release (2.0.1). You can verify your files with some free utilities like http://www.winmd5.com/.

```
MD5 (aria2c.exe) = f8009bf6c9576fc5d016ae8e1c40a442
MD5 (curl-ca-bundle.crt) = 3c58c3f2435598a942dc37cdb02a3ec3
MD5 (curl.exe) = 021982969ea66cdf3f0f12fa1e17aee5
MD5 (udemy-dl.exe) = 1a15b6321d47d73f8bdb4934af6fd2e7
MD5 (youtube-dl.exe) = 82aaacc3414d0512683f3b5d0f20409b
```

**Comment by Shimoli** [comment]
This is the error I get after doing the above correction http://imgur.com/exuz6ON

**Comment by warrendeleon** [comment]
As I said @Shimoli  your terminal is not in the working directory as the udemy-dl.exe. First you have to use comand "cd" to move your working directory to the correct place.

For example, first:

> `cd C:\Users\shimoli\Downloads\udemy-dl`

Or you can open the folder where the installer is, and with SHIFT pressed (do not stop pressing it) right click. You will find an option on the menu list called "open command prompt here". (here is a video showing how to do it: https://youtu.be/ILn9xW6RVNU?t=1m25s

Then, when your cmd is in the same working directory as the udemy-dl.exe, you can use the command:
>`udemy-dl.exe -u yourudemyemail -p yourpassword https://www.udemy.com/yourpaidcourse`

I hope this can help you.
