### ISSUE TITLE
[BUG] AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by warrendeleon** [nishad/udemy-dl-windows#43]
Hello,

I'm trying to download this course that I bought a few weeks ago; https://www.udemy.com/the-complete-ios-9-objective-c-guide-make-20-applications

And I'm getting this error:
![image](https://cloud.githubusercontent.com/assets/6538899/12643433/683d6eb4-c5bc-11e5-89fa-de20545fc29c.png)

Does anyone know a way to solve it?

Thank you very much.

**Comment by nishad** [comment]
Your issue seems to be this one https://github.com/nishad/udemy-dl-windows/issues/37. A quick solution for the time-being is this one https://github.com/nishad/udemy-dl-windows/issues/37#issuecomment-172812223.

**Comment by warrendeleon** [comment]
Thank you @nishad! It's solved now.

**Comment by SiteDesignUSA** [comment]
Tonight I tried to download course (which I bought) and received 

Failed to get course ID

and

Traceback (most recent call last):
  File "<string>", line 374, in <module>
  File "<string>", line 370, in main
  File "<string>", line 294, in udemy_dl
AttributeError: 'NoneType' object has no attribute 'encode'

Errors. I read the other threads and saw the comments about having access to them and I did purchase them.

**Comment by warrendeleon** [comment]
Try to use "--lesson-start"

> `udemy-dl --lecture-start 1 -u username -p password http://www.udemy.com/yourcourse`

**Comment by nishad** [comment]
Duplicate of https://github.com/nishad/udemy-dl-windows/issues/37, closing this thread as part of housekeeping.
