### ISSUE TITLE
No download for several courses

### ISSUE THREAD

**Issue by tobias-p** [nishad/udemy-dl-windows#46]
Hi,

I am having problems with downloading some of my courses I'm enrolled in.
It seems that those courses are taken down from udemy, but I can watch them online without any problems.
One of the courses has following url: https://www.udemy.com/draft/276186
Trying to download that course gives me no error - it is just skipped. Would be great if you could check it out. 

Thx in advance
Tobias

**Comment by surajy** [comment]
This course has been remove

**Comment by tobias-p** [comment]
And there is no way to download the course anyway

**Comment by nishad** [comment]
Udemy forced to take down lot of courses due to piracy. https://medium.com/@robconery/how-udemy-is-profiting-from-piracy-5638b929ffca#.9m2oht1kb

There is nothing can be done within the scope of this tool. You can ask udemy for a refund if you wish.

**Comment by tobias-p** [comment]
well, since i've got this courses via several bundles I think there will be no chance of any refund. But thanks for the info.
