### ISSUE TITLE
Download problem with umlauts in filename

### ISSUE THREAD

**Issue by duracell** [nishad/udemy-dl-windows#5]
There is a problem while downloading files with special characters like german umlauts (äöü).
In this example it should be a "ü".
Course: https://www.udemy.com/derkomplettewebentwicklerkurs/

```
Downloading 018 Alles zusammenf├╝gen HTML Projekt.mp4
Traceback (most recent call last):
  File "<string>", line 288, in <module>
  File "<string>", line 284, in main
  File "<string>", line 225, in udemy_dl
  File "<string>", line 201, in get_video
  File "<string>", line 29, in download
  File "<string>", line 53, in aria2c_dl
  File "C:\Users\Nishad\Desktop\udemy-dl\build\udemy-dl\out00-PYZ.pyz\subprocess
", line 522, in call
  File "C:\Users\Nishad\Desktop\udemy-dl\build\udemy-dl\out00-PYZ.pyz\subprocess
", line 710, in __init__
  File "C:\Users\Nishad\Desktop\udemy-dl\build\udemy-dl\out00-PYZ.pyz\subprocess
", line 958, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 647
: ordinal not in range(128)
```

**Comment by nishad** [comment]
Unfortunately I don't have access to any courses with special characters. If there is any free course with special characters please let me know.  Thanks for letting me know this issue.

**Comment by duracell** [comment]
Thanks for the fast reply.
This is a free course who has the problem in the first video:
https://www.udemy.com/recht-am-eigenen-bild

**Comment by nishad** [comment]
I'll look into it soon. Once I could resolve this issue I'll update this thread. Thanks for the course link.

**Comment by nishad** [comment]
@duracell, I'm sorry that I couldn't find enough time to fix the whole script. Here is a quick fix for the time being. Download an alpha build of `udemy-dl.exe` from here. 
http://cl.ly/csz8/udemy-dl.exe

This version uses builtin downloader to get the video file instead `curl.exe` or `aria2c.exe`. So you need only this `udmey-dl.exe`.

I'll update the main source once I'm free. Till then I'll keep this thread open. And please remember its a temporary fix.

:sake:  Kanpai

**Comment by nishad** [comment]
@duracell, if this fix works for you, please let me know, so I can include this to next planned release.

**Comment by duracell** [comment]
Sorry for the delay. It's works perfect! Download works and the filename is as it should be!
Thanks!

**Comment by rishabh797** [comment]
it says error to few arguments 
![untitled](https://cloud.githubusercontent.com/assets/14950887/10261898/7b33f178-69cd-11e5-8eb5-bee17bbbd75d.png)

**Comment by nishad** [comment]
The screenshot says it is working fine so far. There's no error.

**Comment by rishabh797** [comment]
hmm how should i download udemy courses ??? this cmd comes up for 1 second and then goes ????

**Comment by nishad** [comment]
Usage is example at, please follow that

https://github.com/nishad/udemy-dl-windows/blob/master/README.md

**Comment by rishabh797** [comment]
sorry for inconvenience im a noob . it is wriiten Simply call udemy-dl.exe with the full URL to the course page.

udemy-dl.exe https://www.udemy.com/COURSE_NAME

thats ok but as soon as i click the exe file it comes for one second and then goes. where i should enter the url of course name and id and password 
im really sorry could u plz demonstrate

**Comment by rishabh797** [comment]
plz help

**Comment by nishad** [comment]
Go to the folder of the excecutable in command prompt and in terminal prompt give this whole command.

This script is a command line application, so it needs to be initialised through a command prompt.

**Comment by rishabh797** [comment]
thank you a million times can this also download pdf files and text files

**Comment by rishabh797** [comment]
it says cannot download lecture 
cannot download lecture 
...... plz help

**Comment by rishabh797** [comment]
????

**Comment by nishad** [comment]
Which command you are expecting and what is the exact error showing up ?

**Comment by rishabh797** [comment]
i was downloading paid courses thats why so is there any way to download paid courses any program or anything

**Comment by nishad** [comment]
This tool is not intended to infringe any copyrights of udemy. As the project's description , this will only help to get videos for personal offline use. Mainly due to bandwidth limitations of users from many developing countries. Please pay for the courses and respect udemy's business model.

**Comment by jaan143** [comment]
Sir can you plz create screenshot of problem 
when i click on udemy-dl.exe its open for one second and then close automatically kindly help in screenshot i dont understand plz

**Comment by nishad** [comment]
Please see this comment, it is examples there.
https://github.com/nishad/udemy-dl-windows/issues/5#issuecomment-145242296

**Comment by theTwist84** [comment]
jaan143 it has to be run through command prompt

**Comment by rahmanyazgan** [comment]
Thanks

**Comment by Chlitzxer** [comment]
http://cl.ly/csz8/udemy-dl.exe that one works the best but I wish this can be changed to pull also .pdf .txt and .zip files I have paid courses that have a ton of files attached and I have to check manually each link to download those files not very good option :( Please update that function to pull any format attached thanks :(

**Comment by nishad** [comment]
As the description says the only intention of this tool is to be a a windows utility to download videos from udemy for personal offline use.

There is no plan to extend this tool to be something for making complete copies of udemy courses. Please feel free to fork it and make own changes.

**Comment by nikushev** [comment]
nishad, sorry to bother you but the app stopped working today. Maybe Udemy changed something, it's impossible to download anything.

**Comment by robertw2605** [comment]
Hi Nishad, I have the same issue as nikushev, I just purchased a couple more courses under the $10 deal yesterday, download failed. Last error code I got was;

Cannot download lecture "Arduino and Wii Nunchuck problems - how should it behave?"
Traceback (most recent call last):
  File "<string>", line 288, in <module>
  File "<string>", line 284, in main
  File "<string>", line 215, in udemy_dl
  File "<string>", line 172, in get_video_links
  File "C:\Users\Nishad\Desktop\udemy-dl\build\udemy-dl\out00-PYZ.pyz\encodings. cp437", line 12, in encode
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2019' in position 29: character maps to <undefined>

C:\Users\Robert Wheeler\Downloads\udemy-dl-win>udemy-dl.exe -v
udemy-dl.exe 1.8.0

**Comment by robertw2605** [comment]
Any help greatly appreciated.
