### ISSUE TITLE
Download files in bytes instead of real size

### ISSUE THREAD

**Issue by farazhussain2015** [nishad/udemy-dl-windows#50]
@nishad  , while downloading courses , i found that after downloading few sections , downloader starts to download files in bytes files . any solution?

**Comment by nishad** [comment]
I'm sorry that I couldn't understand, what you have exactly meant.

**Comment by farazhussain2015** [comment]
@nishad  it is not downloading full files/videos after few hours of using . like one video is 50 mb in real size but it is downloading only 345 bytes ..

**Comment by nishad** [comment]
Do it in a pace, one course in a day or so, after all the purchase is life long.
