### ISSUE TITLE
Download resources for a lecture

### ISSUE THREAD

**Issue by mouradxmt** [nishad/udemy-dl-windows#51]
Please there is no possibility to download resource for a lecture , (PURCHASED COURSE)

**Comment by surajy** [comment]
Yes,but you have buy that service

**Comment by mouradxmt** [comment]
How it cost ?

**Comment by mouradxmt** [comment]
I bought courses , But I'm so lazy to download each resource one by one

**Comment by surajy** [comment]
Have you download nishab udemy-dl.py scripts

**Comment by mouradxmt** [comment]
Yeah I did !

**Comment by mouradxmt** [comment]
windows version ! It download videos as well but books & slides and other resources doesn't download

**Comment by surajy** [comment]
Open cmd 
Type udemy-dl.py give course link and then enter 
It will ask you user I'd and password 
Put it and download start

**Comment by mouradxmt** [comment]
Ah , it working , but it download only videos , not resources

**Comment by surajy** [comment]
Sry bro that features is not added
If you want to download any course for free 
Their is one who give script at 25$
If you want contact me at technologylogic1993@gmail.com

You can also get lynda vedio also

**Comment by surajy** [comment]
You can trust me 
Visit this site for demo Www.technolover.tk 
Only one upload for now because my net speed low I will upload later 
But this service is true
If you interested go to contact and mail me

**Comment by nishad** [comment]
@surajy This is an open source project's issue tracking system, not any petty piracy sales forum. Behave yourself. Be ethical and shameful of what you are doing. People like you are destroying the concept of open source. I feel pity for you.

**Comment by surajy** [comment]
First I m not selling I m just helping him

I don't know this will happen and sorry that.
I just want to help him and nothing else not my intention for sale and that.
I just want partner because I want to buy that service and implement your
script to help others.
But the problem is I don't have PayPal account that why I told him.

Sorry sorry for that I will not repeat again

**Comment by surajy** [comment]
You getting me wrong relax I m not what you thinking atleast you can reply

**Comment by mouradxmt** [comment]
Sorry for making this trouble ! 
I'm Asking Mr.Nishad to add these features as downloading materials and resources ! and much more
