### ISSUE TITLE
[BUG] udemy-dl-win: 

### ISSUE THREAD

**Issue by bdcutler** [nishad/udemy-dl-windows#55]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide]().
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [X] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{issue content here}
On several courses, I get the error:

```
Traceback (most recent call last):
  File "<string>", line 374, in <module>
  File "<string>", line 370, in main
  File "<string>", line 294, in udemy_dl
  AttributeError: 'NoneType' object has no attribute 'encode'
```
I can give sample courses if that would help.

Thank you for providing this tool.  When I signed up for Udemy and bought A LOT of ther courses, they advertised the fact you could download for offline viewing.  Sadly, that is not the case - almost none of them.  Being I am in places without WiFi, your tool makes it possible for me to take the courses.  Thank you again!

**Comment by tobias-p** [comment]
This was already several times discussed, Please check here: https://github.com/nishad/udemy-dl-windows/issues/37
