### ISSUE TITLE
[BUG] Update.cmd failed to update

### ISSUE THREAD

**Issue by redlikesu** [nishad/udemy-dl-windows#56]
Hi Nishad,

Whenever i try to update the program it always say update 404 not found and some components gets updated and finally i receive Update.cmd failed.

Attached is the screenshot.

Thanks,
Shabaaz

![update failed](https://cloud.githubusercontent.com/assets/9590703/13218602/bc3370b8-d97b-11e5-9882-e5589d80e970.JPG)
z

**Comment by Vulgaris-Viridis** [comment]
Same here..
curl: (22) The requested URL returned error: 404 Not Found
ERROR : Failed to download latest udemy-dl.exe

curl: (22) The requested URL returned error: 404 Not Found
ERROR : Failed to download latest curl.exe

curl: (22) The requested URL returned error: 404 Not Found
ERROR : Failed to download latest update.cmd

**Comment by nishad** [comment]
Fixed with https://github.com/nishad/udemy-dl-windows/commit/bd3106296286471a47e738fe96e56468c7fd87f6. You may need to run `update.cmd` twice to eliminate all 404 errors. 

Only `update.cmd` is updated, no updates for `udemy-dl.exe` at this moment.
