### ISSUE TITLE
[BUG] Error: Couldn't fetch token !

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [nishad/udemy-dl-windows#57]
Error when attempting to download any course...

**Comment by Vulgaris-Viridis** [comment]
Any updates on this error?

**Comment by emprovements** [comment]
Experiencing the same issue.

**Comment by nishad** [comment]
It's a duplicate issue, already answered in https://github.com/nishad/udemy-dl-windows/issues/63#issuecomment-197439688
