### ISSUE TITLE
[PROPOSAL] Subtitles are not download, i think this is a important function

### ISSUE THREAD

**Issue by Program12345** [nishad/udemy-dl-windows#62]
Dearm 
first of all it should be said that this software makes it much easier for people to study offline courses that bought.
The question I have been proposing, is that I see that there are several courses with subtitles, for example if we are in the web development and filter out to seek only courses with subtitles, will appear a reasonable amount.
And maybe it's not something complex to implement, is it just a srt file?
I bought a course that is legend, and when opening the browser I can enable the subtitle, but to download the video, it is no subtitle, is there any way to download also the subtitle?
Another suggestion, some courses, has pdfs within the chapters and they are usually connected - but other courses instead of "pages" of the pdf has an "article", and it is a html page.
It is possible to udemy-dl-win automatically download with a scraping of a html and save articles as a html page?

Thanks in advanced
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [v] I have read and understood the [contributors guide]().
- [v] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [v] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [v] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{issue content here}

**Comment by YHOYO** [comment]
I think this feature is important too...

**Comment by mouradxmt** [comment]
yes this feature is so important , and also the slides features and ebooks

**Comment by yasserdhia** [comment]
yes this feature is very important....i hope to do this.

**Comment by mouradxmt** [comment]
I think that the fail that I used to work with was patched :( unfortunatly

On 4 April 2016 at 21:56, yasserdhia <notifications@github.com> wrote:

> yes this feature is very important....i hope to do this.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/nishad/udemy-dl-windows/issues/62#issuecomment-205493283>
>



-- 
*Cordialement .*

*Mourad Mtouaa *

**Comment by nishad** [comment]
Implemented in v2.1.1, with https://github.com/nishad/udemy-dl-windows/releases/tag/v2.1.1
