### ISSUE TITLE
please tell me how to install udemy-dl using the tar file

### ISSUE THREAD

**Issue by kumarbibek42** [nishad/udemy-dl-windows#65]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [ ] I have read and understood the [contributors guide]().
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{issue content here}

**Comment by nishad** [comment]
This project intended to be a binary release of `udemy-dl`. This issue is invalid for this project.
