### ISSUE TITLE
When i want download from udemy with udemy-dl i need a link . for this link i have to click on Start Free Preview but now when i want download from udemy and i click on Start Free Preview  i see this error : javascipt:void(0) . what should i do ? can you help me for i bring link with another way ? please guide me . 

### ISSUE THREAD

**Issue by reza147** [nishad/udemy-dl-windows#71]
[Please] prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [ ] I have read and understood the [contributors guide]().
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{issue content here, replace this line with your issue content}

**Comment by elmatadoor** [comment]
save issus with me on mozilla firefox

**Comment by reza147** [comment]
Hi dear friend elmatadoor . please help me . 
I ask you that you test my problem in udemy . choose a course and click on the ((Start Free Preview)) .
you see this error :  javascipt:void(0)

please guide me . what do you mean that you say ((save issus with me on mozilla firefox)) ?
i can not understand .

**Comment by elmatadoor** [comment]
@reza147 , yes i have the same problem as you

**Comment by reza147** [comment]
Thank you for your answer . 
Ok . do have idea for solve this problem ?

**Comment by elmatadoor** [comment]
@reza147 , i don't think this time the issus will be solved , because the udemy update his API duo to lot of DMCA complain that was receaved , because  have see a lot of videos on youtube was removed duo to DMCA and i have seen a lot of commerical tools named udemydownloader stope working and no update was released by the develloper , we are waiting @nishad , to clarifie this issus and fixed it if possible

**Comment by reza147** [comment]
but when one person want buy a course from udemy . he/she should see a preview of that course . 
really i can not understand why udemy do this work !!!!!!!!!!!!!!!

**Comment by elmatadoor** [comment]
Have You Alreadu download somme webdev course , i can create a torrent for you for my cources , and you do the same thing to exchange our courses

**Comment by reza147** [comment]
yes i ready . very good .

**Comment by elmatadoor** [comment]
send me your email on private mssage , is there private message option here

**Comment by reza147** [comment]
Thank you so much . No problem this is my email address : koroshkabir710@yahoo.com

**Comment by reza147** [comment]
I send you a mail . i wait for your answer . thank you .

**Comment by nishad** [comment]
@reza147 , @elmatadoor , This is an open source project's issue tracking system, not any piracy forum. Behave yourself. Be ethical and shameful of what you are doing. People like you are destroying the concept of open source. I feel pity for you. udemy-dl project is is neither intended to breach any udemy-dl copyrights not it's commercial policies. 

All future issue reports from these users will get ignored.
