### ISSUE TITLE
[BUG] Failed to get course ID

### ISSUE THREAD

**Issue by pathankp** [nishad/udemy-dl-windows#72]
it seems Udemy updated their site now there is no more timer in preview, kindly fix this issue as soon as possible.

**Comment by alialpha123** [comment]
yes please

**Comment by pathankp** [comment]
is there any updates?

**Comment by elmatadoor** [comment]
yes , same issus here , we are waiting @nishad to replay our issues

**Comment by Abdelraman** [comment]
yes, same issue happens here, kindly try to fix it. Thanks

**Comment by nishad** [comment]
All issues should contain mandatory check lists. Issues reported without checklists will be closed or ignored.
