### ISSUE TITLE
Too many arguments error in Windows 10

### ISSUE THREAD

**Issue by soamz** [nishad/udemy-dl-windows#74]
HI, i just downloaded your latest zip. 
Im on windows 10. 
When I try to udemy.-dl.exe the black screen comes and goes in a flash in nanosecond.

but I could still manage to see in split second, what is showing and going.

It was:
udemy-dl.exe error : Too many arguments. 

How do I open the app and get it working ?

**Comment by nishad** [comment]
Already answered in https://github.com/nishad/udemy-dl-windows/issues/38#issuecomment-172749630
