### ISSUE TITLE
Stopped from half, how to download the rest ?

### ISSUE THREAD

**Issue by soamz** [nishad/udemy-dl-windows#76]
All works amazing!
I just bought a Cisco course which is like 18GB for 127 exercises. 

It has downloaded from 1 to 15 folders, each folder has like 6 videos.

Now, it has failed after 15. 

How do I download the rest ?
Whats the command ?

**Comment by nishad** [comment]
All issues should contain mandatory check lists and proper prefix for the subject line. Issues reported without checklists or without proper prefix will be closed or ignored.

Due to this policy I'm closing this thread.
