### ISSUE TITLE
[QUESTION] Stopped from half, how to download the rest ?

### ISSUE THREAD

**Issue by soamz** [nishad/udemy-dl-windows#77]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

All works amazing!
I just bought a Cisco course which is like 18GB for 127 exercises.

It has downloaded from 1 to 15 folders, each folder has like 6 videos.

Now, it has failed after 15.

How do I download the rest ?
Whats the command ?

![screenshot_1](https://cloud.githubusercontent.com/assets/2391697/13898313/47d89c3e-edf3-11e5-935d-500fe12257ba.png)

**Comment by nishad** [comment]
You can use --lecture-start parameter to start from a specific lecture. 

See here for detailed instructions https://github.com/nishad/udemy-dl-windows/blob/master/README.md#advanced-usage

**Comment by nishad** [comment]
If your issue persist, even after using `--lecture start` you can delete `aria2c.exe`, to use curl. You can even delete both `aria2c.exe` and `curl.exe` to use built-in downloader. 

This is explained in https://github.com/nishad/udemy-dl-windows/blob/master/README.md#downloader under the heading of **Downloader**.
