### ISSUE TITLE
[PROPOSAL] A slight modification to the -o argument

### ISSUE THREAD

**Issue by thefinalwolf** [nishad/udemy-dl-windows#78]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Hello, I love this tool and have used it quite a few times for the courses I bought just in case they get taken down (which has happened before).
I am suggesting a slight modification to the '-o' argument. When I don't use the -o, it will download to %HOMEPATH%\course-name, but when I do use -o it will only go to the specified output. 
(ex: **OUTPUT**\01-lesson 1).

I think it would more useful to have the output path auto-include the course name along with the user's specified output directory (or at least a modifier to make it optional)
(ex: **OUTPUT**\\**course-name**\01-lesson 1)

The change would make it much easier keeping the courses organized without having to type in each individual course name every time.

**Comment by nishad** [comment]
Thanks for pointing this out @thefinalwolf, 
As per https://github.com/nishad/udemy-dl/commit/455f06857a97f5e17c31f42e2e33f536c9381f20, `-o` or `--output` is common for `Output directory / text file path (if saving links)`, so it is applicable for `-l` as well.

`-o` does precisely, what is says. Insted of using `-o`, you can `cd` into the destination directory and run `udemy-dl.exe` to auto-create the download folder. You can add `udemy-dl-windows` directory to `%PATH%` for getting this command from any directory.

**Comment by thefinalwolf** [comment]
@nishad Ah, I see. I didn't consider the whole 'puts in current directory' thing that scripts normally do. Don't know how I overlooked that. Thanks!
