### ISSUE TITLE
Getting Answer: This Application can't run

### ISSUE THREAD

**Issue by robertlito** [nishad/udemy-dl-windows#79]
[QUESTION]**.
I am getting the following answer from Windows: This app can't run on your PC.
I am using Windows 10.

**In raising this issue, I confirm the following (please check boxes):**

- [X ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ X] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{issue content here, replace this line with your issue content}

**Comment by nishad** [comment]
Right now, This project requires minimum 6 checks are mandate in an issue report. You may need to use proper prefix for the subject line as well. 

Due to this policy I'm closing this issue. Feel free to reopen, once you complete the checklist and after finishing the required edits.
