### ISSUE TITLE
Keep numbering of chapters same as on the site

### ISSUE THREAD

**Issue by Ryan147** [nishad/udemy-dl-windows#8]
Since the utility is not able to download pdf/txt/quizes (yet) is it possible to keep numbering of the downloaded files the same as on the site? 

Or somehow give notice that it skips certain files because they are not videos?

**Comment by nishad** [comment]
Dear @Ryan147, as the description says the only intention of this tool is to be a `a windows utility to download videos from udemy for personal offline use `.

There is no plan to extend this tool to be something for making complete copies of udemy courses. Please feel free to fork it and make own changes.

:sake:

**Comment by Ryan147** [comment]
Ok thank you for that!

**Comment by elmatadoor** [comment]
Hello nishad , i am a beginer coder
i need to know if this tool is 100% open source , so people can amelior it , if yes where i can find the source code
should i be expert in python to edit it as my own customisation
excuse me i am not a pro and my be my question are beginer skill
