### ISSUE TITLE
[QUESTION] This application can't run

### ISSUE THREAD

**Issue by robertlito** [nishad/udemy-dl-windows#80]
**In raising this issue, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [X ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X ] I have checked that the issue I'm posting isn't already reported.
- [X ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [X ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [X ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

I am getting the following answer from Windows: This app can't run on your PC. To find a version for your PC, check with the software publisher. It actually worked about 2 weeks ago and I could download a full course. 
I am using Windows 10.

**Comment by nishad** [comment]
According to the latest automated tests in Windows 10 VM, current release works perfectly. I'll investigate if similar issues are reported by different users.

**Comment by robertlito** [comment]
Maybe this can help you? Take a look at the screenshot of what I actually type. 
It doesn't ask me for the username and password but gives me that blue answer right away.
Could it be I am typing the wrong url for the course? This is the url I get when I click on Start Free Preview on the course page:
http://screencast.com/t/DFtenYJif

**Comment by nishad** [comment]
This is the only possible solution for the time being https://github.com/nishad/udemy-dl-windows/issues/42#issuecomment-176550204.

**Comment by letuananh035** [comment]
It Is Not Working Now. "FAILED TO GET COURSE ID"

**Comment by nishad** [comment]
That means, this issue is resolved, and the tool is working in your windows. For your previous comment please see https://github.com/nishad/udemy-dl-windows/issues/63#issuecomment-197439688
