### ISSUE TITLE
Error when Download

### ISSUE THREAD

**Issue by emadhamdi89** [nishad/udemy-dl-windows#82]
![error when download](https://cloud.githubusercontent.com/assets/18100894/14065724/7c14028e-f435-11e5-86dd-9d075c1d1268.PNG)

**Comment by nishad** [comment]
All issues should contain mandatory check lists and proper prefix for the subject line. Issues reported without checklists or without proper prefix will be closed or ignored.

Due to this policy I'm closing this thread. You are free to reopen this issue after making sufficient edits
