### ISSUE TITLE
[Question] Failed to get course ID

### ISSUE THREAD

**Issue by RaxXxz0r** [nishad/udemy-dl-windows#85]
I get the error failed to get course ID

My version is 2.0.1
My operating system is Windows 7

This is was I always get:

C:\Users\Admin\Desktop\Udemy>udemy-dl.exe -u example@gmail.com -p password http://www.udemy.com\MyUdemyCourse
Downloading to: C:\Users\Admin\Desktop\Udemy\MyUdemyCourse

Failed to get course ID

What can I do?
Thanks for help

**Comment by nishad** [comment]
**All issues should contain mandatory check lists and proper prefix for the subject line. Issues reported without checklists or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can reopen this issue after making sufficient changes.
