### ISSUE TITLE
Problem to download see below

### ISSUE THREAD

**Issue by Shimoli** [nishad/udemy-dl-windows#87]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Ai>udemy-dl.exe
'udemy-dl.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Ai>

**Comment by nishad** [comment]
**All issues should contain mandatory check lists and proper prefix for the subject line. Issues reported without checklists or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can reopen this issue after making sufficient changes.
