### ISSUE TITLE
"Failed to get course ID" using Udemy recently updated user interface

### ISSUE THREAD

**Issue by mikeatgithub** [nishad/udemy-dl-windows#89]
**[BUG]**
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [ ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ x] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**[BUG]**
I have used "udemy-dl.exe" before successfully a few times before with no issues. However, Udemy has changed its user interface completely. When I used "udemy-dl.exe" utility with the new user interface  I got the error "Failed to get course ID". The following is what I entered and the result I got.

C:\Users\Dell\Desktop\Udemy_dnld>udemy-dl.exe -u (my username i.e. my email without parenthesis) -p (my password  without parenthesis) https://www.udemy.com/understand-nodejs/learn/v4/t/lecture/3453110?start=2

Downloading to: C:\Users\Dell\Desktop\Udemy dnld\understand-nodejs

Failed to get course ID

**Comment by tobias-p** [comment]
Congratulations, this bug was already posted and you "checked" that the bug you are posting wasnt already posted? ;)

**Comment by nishad** [comment]
**All issues should contain mandatory check lists and proper prefix for the subject line. Issues reported without checklists or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request ti reopen this issue after making sufficient changes.
