### ISSUE TITLE
[BUG] 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by teplovdi** [nishad/udemy-dl-windows#96]
Version : udemy-dl 2.1.1

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl-windows/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed tab](https://github.com/nishad/udemy-dl-windows/issues?q=is%3Aissue+is%3Aclosed)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [x] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---
Windows 10x64

udemy-dl.exe https://www.udemy.com/plan-and-deploy-exchange-2016/
Username / Email : ***@***.***
Password :
[INFO-881] Downloading to: C:\Users\Ice\Downloads\udemy-dl-win-2.1.1\plan-and-deploy-exchange-2016

[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 691286
Getting course data: 100.00% [====================] Done

Downloading Video: 001 Функционал Exchange Server 2016

[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 886, in <module>
  File "<string>", line 883, in main
  File "<string>", line 742, in udemy_dl
  File "<string>", line 645, in get_data
  File "<string>", line 604, in get_video
  File "<string>", line 618, in check_downloaded
  File "download.py", line 30, in download
  File "download.py", line 80, in aria2c_dl
  File "subprocess.py", line 522, in call
  File "subprocess.py", line 710, in __init__
  File "subprocess.py", line 958, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode characters in position 338-347: ordinal not in range(128)
None
udemy_dl returned -1

**Comment by nishad** [comment]
Could you try with `--safe-file-names`.

**Comment by teplovdi** [comment]
Working, sorry for waste your time.
